name: Composite Explorer
analytics: {}
github: true
author:
  name: Anna Madra
  email: annakopov@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.7111775120720267
color:
  lightness: 0.9940187414176762
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  saturation: 0.1657394964713603
  brandStrength: 0.04070854466408491
  rhythmicContrast: 0.3079941051546484
content_rating:
  adult: false
typography_spectrum: 0.9005883666686714
opengraph: {}
